# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Instagram Clone Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram Clone Demo
  pod 'Bolts'
  pod 'Parse'

end
